@id = 5d651c082c64b349d4dd0afc
GET http://localhost:3001/notes/

###
GET http://localhost:3001/notes/{{id}}

###
POST http://localhost:3001/notes/add   HTTP/1.1 
Content-Type: application/json

{
    "title": "Trip to Manchester", 
    "text": "Buy tickets, flight and book the flat. Remember check insurace",
    "date": "2019-05-29T21:19:15.187Z"
}

###
PUT http://localhost:3001/notes/update/{{id}} HTTP/1.1 
Content-Type: application/json

{
    "title": "Trip to Japon",
    "text": "Call the insurace company",
    "date": "2019-07-30T21:19:15.187Z"
}

###
DELETE Http://localhost:3001/notes/{{id}}

###

