@id = 5d63cfc5763ee73f22e6043d
GET http://localhost:3001/notes/

###
GET http://localhost:3001/notes/{{id}}

###
POST http://localhost:3001/notes/add   HTTP/1.1 
Content-Type: application/json

{
    "title": "Trip to Spain", 
    "text": "Buy tickets, flight and book the flat. Remember check insurace",
    "date": "2019-07-29T21:19:15.187Z"
}

###
POST http://localhost:3001/notes/update/{{id}} HTTP/1.1 
Content-Type: application/json

{
    "title": "Trip to Spain",
    "text": "Call the insurace company",
    "date": "2019-07-29T21:19:15.187Z"
}

###
DELETE Http://localhost:3001/notes/{{id}}

###

